<?php

namespace NotificationsBundle\DAO;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNotificationsForUser($user)
	{
		$query = $this->getEntityManager()->createQuery(
			'SELECT  *
			 from NotificationsBundle:ReplyNotification reply
			 where reply.userTo = 1 
			'
			);
		return ($query->getResult());
	}
}
