<?php

namespace BackendBundle\DAO;

/**
 * FounderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FounderRepository extends \Doctrine\ORM\EntityRepository
{
}
