<?php

namespace BackendBundle\DAO;

/**
 * UserPointsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPointsRepository extends \Doctrine\ORM\EntityRepository
{
}
